title: Discord Bot Commissions
author: Seiyria
email: discord@seiyria.com
description: >-
  Discord Bot Commissions is a service that offers you the ability to commission your own Discord bot.
  We take it through every stage: design, development, and optionally hosting!
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://discord.seiyria.com" # your site's origin, e.g. https://forestry.io

# Build settings
defaults:
  - scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default" # this ensures all content renders with layouts/default.html

plugins:
  - jekyll-feed
  - jekyll-menus

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
